apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - demo-banner.yaml
  - generated-audio-pvc.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
  - cronjob.yaml
