apiVersion: apps/v1
kind: Deployment
metadata:
  name: clara-web
  namespace: clara-voiceops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clara-web
  template:
    metadata:
      labels:
        app: clara-web
    spec:
      containers:
        - name: web
          image: clara-web:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: clara-web
  namespace: clara-voiceops
spec:
  type: NodePort
  selector:
    app: clara-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
